name: Minimal Android CI Workflow

on:
  push:
    branches:
      - 11-config-github-action-build-apk
      - 12-config-action-upload-apk-to-google-play
    tags:
      - 'v*'

jobs:
  build:
    name: Generate APK

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3.3.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace

    - name: Download a Build Artifact
      id: download
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: ./app/build/outputs/apk/debug/app-debug.apk
