## 1
name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  push:
    branches:
      - 11-config-github-action-build-apk
      - 12-config-action-upload-apk-to-google-play
    tags:
      - 'v*'

## 2
jobs:
  ## 3
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unit tests
        run: ./gradlew test
  ## 4
  android_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest