## 1
name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  push:
    branches:
      - 11-config-github-action-build-apk
      - 12-config-action-upload-apk-to-google-play
    tags:
      - 'v*'

## 2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode base64 to keystore file
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'keystore.jks'
          fileDir: './app/'
          encodedString: ${{ secrets.SIGNING_KEY }}

      - name: Create and populate key.properties file
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          touch key.properties
          echo keyAlias="$ALIAS" >> key.properties
          echo keyPassword="$KEY_PASSWORD" >> key.properties
          echo storePassword="$KEY_STORE_PASSWORD" >> key.properties
          echo storeFile="keystore.jks" >> key.properties
        shell: bash

      # 2
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      # 3
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      # 4
      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      # 5
      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt
